alloy:
  configMap:
    create: true
    content: |
      logging {
        level = "info"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      prometheus.scrape "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [prometheus.remote_write.mimir.receiver]
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.lgtm.receiver]
      }

      prometheus.remote_write "mimir" {
        endpoint {
          url = "http://tabletap-monitor.taila459ef.ts.net:9009/api/v1/push"
        }
      }

      loki.write "lgtm" {
        endpoint {
          url = "http://tabletap-monitor.taila459ef.ts.net:3100/loki/api/v1/push"
        }
      }

controller:
  type: daemonset
  # Add the Tailscale ProxyClass annotation
  podAnnotations:
    tailscale.com/proxy-class: "alloy-egress"

mounts:
  varlog: true
  dockercontainers: true