alloy:
  configMap:
    create: true
    content: |
      logging {
        level = "debug"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      prometheus.scrape "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [prometheus.remote_write.mimir.receiver]
        
        rule {
          source_labels = ["__meta_kubernetes_pod_annotation_k8s_grafana_com_scrape"]
          action        = "keep"
          regex         = "true"
        }
        
        rule {
          source_labels = ["__address__", "__meta_kubernetes_pod_annotation_k8s_grafana_com_metrics_port"]
          action        = "replace"
          regex         = "([^:]+)(?::\\d+)?;(\\d+)"
          replacement   = "$1:$2"
          target_label  = "__address__"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.write.lgtm.receiver]
      }

      prometheus.remote_write "mimir" {
        endpoint {
          url = "http://lgtm-proxy.monitoring.svc.cluster.local:9009/api/v1/push"
        }
      }

      loki.write "lgtm" {
        endpoint {
          url = "http://lgtm-proxy.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }

controller:
  type: daemonset

mounts:
  varlog: true
  dockercontainers: true