apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose-app.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: table-8
  name: table-8
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: table-8
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose-app.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: table-8
    spec:
      containers:
        - env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tabletap-monitor.taila459ef.ts.net:4317
            - name: OTEL_SERVICE_NAME
              value: table-8
          image: ghcr.io/kchenfs/tableai:table-8
          name: table-8
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
