apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose-app.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: table-3
  name: table-3
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: table-3
